### ISSUE TITLE
bad discord bot permissions makes matrix bot irrevocably broken

### ISSUE THREAD

**Issue by SIR-unit** [git-bruh/matrix-discord-bridge#8]
I added the discord bot to a (discord) server and bridged a text channel, but didn't give it the proper permissions.  This caused the bridge to give the following traceback:
```
Traceback (most recent call last):
  File "/mnt/drive/space/mx-disc-appservice-env/lib/python3.9/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/mnt/drive/space/mx-disc-appservice-env/lib/python3.9/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/home/z/matrix-discord-bridge/appservice/misc.py", line 28, in wrapper
    return fn(self, *args, **kwargs)
  File "/home/z/matrix-discord-bridge/appservice/appservice.py", line 87, in receive_event
    self.handle_event(event)
  File "/home/z/matrix-discord-bridge/appservice/appservice.py", line 66, in handle_event
    func(obj)
  File "/home/z/matrix-discord-bridge/appservice/main.py", line 109, in on_message
    webhook = self.discord.get_webhook(
  File "/home/z/matrix-discord-bridge/appservice/main.py", line 616, in get_webhook
    webhooks = self.send("GET", f"/channels/{channel_id}/webhooks")
  File "/home/z/matrix-discord-bridge/appservice/misc.py", line 49, in wrapper
    raise RequestError(
errors.RequestError: Failed to get response from 'https://discord.com/api/v8/channels/421097709643104260/webhooks?':
b'{"message": "Missing Permissions", "code": 50013}'
127.0.0.1 - - [09/Jun/2021 03:18:27] "PUT /transactions/77?access_token=abcd1234 HTTP/1.1" 500 778
```
After this the matrix bridge would relay messages from discord to matrix, but not back the other way.  Restarting the service did not fix it.  This gave me the bright idea to rm my .db file and now it won't work at all...  It doesn't remember the association of the discord text channel with the old matrix room (expected) but when I try to re-bridge I get the following traceback
```
Traceback (most recent call last):
  File "/mnt/drive/space/mx-disc-appservice-env/lib/python3.9/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/mnt/drive/space/mx-disc-appservice-env/lib/python3.9/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/home/z/matrix-discord-bridge/appservice/misc.py", line 28, in wrapper
    return fn(self, *args, **kwargs)
  File "/home/z/matrix-discord-bridge/appservice/appservice.py", line 87, in receive_event
    self.handle_event(event)
  File "/home/z/matrix-discord-bridge/appservice/appservice.py", line 66, in handle_event
    func(obj)
  File "/home/z/matrix-discord-bridge/appservice/main.py", line 100, in on_message
    self.handle_bridge(message)
  File "/home/z/matrix-discord-bridge/appservice/main.py", line 69, in handle_bridge
    self.create_room(channel, message.sender)
  File "/home/z/matrix-discord-bridge/appservice/main.py", line 206, in create_room
    resp = self.send("POST", "/createRoom", content)
  File "/home/z/matrix-discord-bridge/appservice/misc.py", line 49, in wrapper
    raise RequestError(
errors.RequestError: Failed to get response from 'http://127.0.0.1:8008/_matrix/client/r0/createRoom?access_token=1234abcd':
b'{"errcode":"M_ROOM_IN_USE","error":"Room alias already taken"}'
127.0.0.1 - - [09/Jun/2021 03:32:57] "PUT /transactions/113?access_token=abcd1234 HTTP/1.1" 500 779
```
Which seems to prevent it from bridging at all.  I tried restarting synapse and the discord bridge.  I can't remove the bot from the existing bridged rooms because we have the same permissions level (admin), so I don't even know how to recover from this bug short of resetting my synapse server, which I would like to avoid.  Any help is appreciated

**Comment by git-bruh** [comment]
You didn't need to delete the db at all, since the appservice would keep retrying and eventually succeed when it got the proper permissions for webhooks.

For the room, kicking the appservice won't help this case anyways since the room has already been created. You can manually create the entry to add a relation between the discord channel and matrix room:

Assuming the discord channel id to be `421097709643104260`, the appservice would've created a room with the alias `#_discord_421097709643104260:domain.tld`. So you just need to get the room ID of that alias from your client (In element just click on the room info and find "This room's internal ID" which looks something like `!djsandjkasndj:domain.tld`.

Now, run the following commands:

```
-> sqlite3 bridge.db
SQLite version 3.35.5 2021-04-19 18:32:05
Enter ".help" for usage hints.
sqlite> INSERT INTO bridge (room_id, channel_id) VALUES ("!djsandjkasndj:domain.tld", "421097709643104260")
   ...> 
# Send Ctrl + D to indicate EOF and finish the transaction.
```

But you'll have another issue as the bridge won't know how many Discord users have been bridged to matrix. If only a few dummy accounts have been created then it should be relatively easy to fix too:

* Find the users added/invited to the already created room and get their MXID's. Their MXIDs look like `@_discord_781097709743105260:domain.tld`.

* Run the following commands for each MXID (The part after `discord_` is the discord ID):

```
-> sqlite3 bridge.db 
SQLite version 3.35.5 2021-04-19 18:32:05
Enter ".help" for usage hints.
sqlite> INSERT INTO users (mxid) VALUES ("@_discord_781097709743105260:domain.tld")
   ...> 
```

There is no need to update the displaynames/avatar urls of these db users since the appservice will sync them.�

**Comment by SIR-unit** [comment]
Awesome, I'll try that later today.  On a side note, is webhooks the only permission my discord bot needs?  I assumed it would need send/read messages, no?  Or is it assumed that that is handled by general server permissions/whatever role the discord bot has?

**Comment by git-bruh** [comment]
I think only "Manage webhooks" should be enough given that the bot has read access to the channel, since it's sending and deleting messages from it's own webhook, not anything else.

Other than that you need privileged intents enabled https://discordpy.readthedocs.io/en/latest/intents.html#privileged-intents, they're required for the bot to receive username/avatar update events.﻿

**Comment by SIR-unit** [comment]
Hmm, I still get the same traceback as before (last one).  To be precise, I re-deleted my .db and started main.py to make sure the .db was fresh, stopped main.py, added entries with sqlite3, then restarted main.py.  This caused the appropriate channel to give a "user#1234 and 3 others chared their avatar", which made it seem like it was working, but bridging still won't work and I get the same traceback (Room alias already taken).

**Comment by git-bruh** [comment]
Something must've gone wrong in the first room ID step, since the appservice first checks if the given channel is already bridged, and proceeds only if it isn't bridged https://github.com/git-bruh/matrix-discord-bridge/blob/3a526f8767071e4580a28b8996b8a07604f1cda3/appservice/main.py#L57

Could you confirm the output of this command ?
```
SQLite version 3.35.5 2021-04-19 18:32:05
Enter ".help" for usage hints.
sqlite> SELECT * FROM bridge
   ...>
!5bg3zjFEMuDOrLo6:domain.tld|813202331872788490
!cAof7rphhaWHIAZs:domain.tld|813119972486283325
```

Make sure that the channel ID you entered is 18 digits long.

**Comment by SIR-unit** [comment]
Here is the output:
```
SQLite version 3.35.5 2021-04-19 18:32:05
Enter ".help" for usage hints.
sqlite> SELECT * FROM bridge
   ...>
!jRVqCBXZjSoAoSGzNL:domain.tld|613148461042237486
```
(I replaced the actual domain with "domain.tld")
I double checked, and the room id is in fact:  !jRVqCBXZjSoAoSGzNL:domain.tld
discord channel id (all 18 digits): 613148461042237486

Originally, I had multiple bridges, but I was trying to just get one bridge up and running.  Do you think the problem could be that it sees my other !bridge commands from the 1:1 chat history and tries to recreate them all?  The bridge isn't fixed in the room I DID try to rebridge

EDIT:  I tried bridging the rest of the users/channels like you suggested, still doesn't work:
```
QLite version 3.35.5 2021-04-19 18:32:05
Enter ".help" for usage hints.
sqlite> SELECT * FROM bridge
   ...>

!jRVqCBXZjSoAoSGzNL:domain.tld|613148461042237486
!hNxBshxTIpwfCjsJlV:domain.tld|617253837660487687
!UlqGStIXwbCRorVakA:domain.tld|421097709643104260
```

**Comment by SIR-unit** [comment]
Oh wow, all the messages went through at once.  Now messages come through just fine.  Thanks for all your help!!  I hope I can contribute in the future.

**Comment by git-bruh** [comment]
That's great to hear! Feel free to open issues in the future aswell.﻿
